#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

feh --bg-fill $HOME/.config/coldRipple.jpg &
$HOME/.config/polybar/launch.sh &
dunst &
picom &
mpd &
